### ISSUE TITLE
Scripting?

### ISSUE THREAD

**Issue by EHotwagner** [matthid/s2client-dotnet#2]
I would like to use this library in an interactive scripting environment but am running against walls using your core 2.0 library with fsi. 
`Library.fs(7,9): error FS0074: The type referenced through 'System.Collections.IComparer' is defined in an assembly that is not r
eferenced. You must add a reference to assembly 'netstandard'.`

I manually referenced `netstandard.dll` to no avail.

Is there a way to do it at the moment?

**Comment by matthid** [comment]
With scripting I assume you mean F# interactive. Yes it should be possible. The easiest will be to wait for a fsi which is compiled against/runs on net471 which supports netstandard 20.

Short them it is probably easier to re-target the library to the current full framework (and add some ifdefs if required)

Technically, another way would be to retartget the library to a lower netstandard, like netstandard 16. But I think that could be in fact more work...

So I currently I don’t have an “just do that” answer. Ideally we will have a netcore based fsi soon (but don’t count on that anytime soon)

**Comment by EHotwagner** [comment]
That's what i also thought.
So i will just retarget the library and wait for a new fsi.
Thanks a lot.

**Comment by matthid** [comment]
As my plan is to release a nuget package (because of #1), I'll try to make that nuget package contain a full framework build to solve this issue as well. Therefore I'll keep it open for now.

**Comment by matthid** [comment]
We released https://www.nuget.org/packages/s2client-dotnet which contains a `net46` build which should work for scripting.
