### ISSUE TITLE
Small problems in build script and documentation

### ISSUE THREAD

**Issue by EasyBusinessNZ** [matthid/s2client-dotnet#3]
Hi, this project looks great and what I have been waiting for. In the build documentation, I noticed a couple of issues when getting things to run.

Running the build.fsx to get I needed to manually create a docs folder with a Release_notes.md that wasn't blank for the build to work.

Running the test projects the paths are not quite correct if assuming the command window is in the root folder. The two steps would need to be 

- dotnet run --project src/s2client-testCSharp/s2client-testCSharp.csproj
- dotnet run --project src/s2client-test/s2client-test.fsproj

**Comment by matthid** [comment]
Yes one problem was that the `RELEASE_NOTES.md` was gitignored. Thanks for reporting.

**Comment by matthid** [comment]
Thanks for letting me know, should be fixed now :)
