### ISSUE TITLE
Cannot access pathing_grid and placement_grid from gamestate object

### ISSUE THREAD

**Issue by EasyBusinessNZ** [matthid/s2client-dotnet#4]
I am trying to access the placement_grid and pathing_grid from the game_state object but do not appear to be able to access those properties. They appear to be in the raw.proto in the StartRaw message but I cannot infer how to access them during a turn.

**Comment by SimonPrins** [comment]
I am having the same issue. From the looks of it, the placement_grid etc. can be accessed from the ResponseGameInfo message. You get this by sending a RequestGameInfo message. From the looks of it, this is not yet implemented in the dotnet api. I intend to create a pull request for this sometime soon.

**Comment by matthid** [comment]
Closed with #5
